from enum import Enum


class Module_Type(Enum):

    BASE = 'BASE'
    SEC = 'SEC'
    PEI_CORE = 'PEI_CORE'
    PEIM = 'PEIM'
    DXE_CORE = 'DXE_CORE'
    DXE_DRIVER = 'DXE_DRIVER'
    DXE_RUNTIME_DRIVER = 'DXE_RUNTIME_DRIVER'
    DXE_SAL_DRIVER = 'DXE_SAL_DRIVER'
    DXE_SMM_DRIVER = 'DXE_SMM_DRIVER'
    SMM_CORE = 'SMM_CORE'
    UEFI_DRIVER = 'UEFI_DRIVER'
    UEFI_APPLICATION = 'UEFI_APPLICATION'
    USER_DEFINED = 'USER_DEFINED'
    UNDEFINED = 'UNDEFINED'

    @classmethod
    def has_element(cls, arg: str) -> bool:
        return arg.upper() in ['UNDEFINED', 'BASE', 'SEC', 'PEI_CORE', 'PEIM', 'DXE_CORE', 'DXE_DRIVER', 'DXE_RUNTIME_DRIVER', 'DXE_SAL_DRIVER', 'DXE_SMM_DRIVER', 'SMM_CORE', 'UEFI_DRIVER', 'UEFI_APPLICATION', 'USER_DEFINED']
